version: "3"

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./petfinder-backend
    container_name: petfinder_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./petfinder-backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    command: >
      sh -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
