# Generated by Django 5.0.6 on 2025-02-05 01:07

import uuid
from django.db import migrations, models

def generate_tokens(apps, schema_editor):
    Animal = apps.get_model("animals", "Animal")
    for animal in Animal.objects.all():
        animal.access_token = uuid.uuid4()
        animal.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Outro', 'Outro')], max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='animal_photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('access_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
            ],
        ),
        migrations.RunPython(generate_tokens),
    ]
