# Generated by Django 5.0.6 on 2025-02-05 01:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
