# Generated by Django 5.0.6 on 2025-02-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
